### ISSUE TITLE
Use properties for variables of abstract classes or use setter/getters.

### ISSUE THREAD

**Issue by szijerveld** [RUGSoftEng/2017-Hestia-Server#18]
Currently we have a mix between properties and getters and setters for our variables in our abstract classes. We should use either the one or the other.

**Comment by LucvandenBrand** [comment]
I see you point for having properties, as it is the 'official' way. However, I personally believe it depends on how your attributes are being used. 
I tend to find it more clear to have a method such as getDevices(), as it follows the nice and clean convention of reserving a verbs to methods, names for classes and attributes. When most if not all attributes are requested in non-repetitve manner, this still makes sense, not?
Now, when of course you expect your attributes to be referenced often (even though this might also indicate high coupling, in which case you have another problem entirely), properties are the solution.
There is indeed some inconsistency in the code regarding this, so try to stick to one horse and I'll be happy in either case. In doubt, **go with properties**, it's always safe to do what the other's do ;)

**Comment by LucvandenBrand** [comment]
You should also look at what your dependencies do, as you'll use their methods in your code: you'll have more consistent/readable code if you adhere to their design choices (_sometimes_).
