### ISSUE TITLE
Find out how to seperate resources into different files.

### ISSUE THREAD

**Issue by szijerveld** [RUGSoftEng/2017-Hestia-Server#26]
Currently, we can not move resources of one namespace into separate files.
The only reason why it works in the devices namespace is because their is an internal dependency chain. between all the classes (Devices->Device->Activator).
For the plugins this will not be the case so we have the problem that we cannot separate the resources into different files.

**Comment by szijerveld** [comment]
@Lukeslux since you are working with Flask and since I think that flask has the same problem. 
Do you know a solution for this.

**Comment by LucvandenBrand** [comment]
In classic flask, you divide your python in multiple modules, have a look at:
- Flask doc section about it: http://flask.pocoo.org/docs/0.12/patterns/packages/
- The Blueprints approach (if it will not clash with your flask restplus approach) http://flask.pocoo.org/docs/0.12/blueprints/#blueprints
