### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by szijerveld** [RUGSoftEng/2017-Hestia-Server#49]
As the README was written by me there are still a lot of spelling and stupid mistakes in them.
This needs to be cleaned up before we hand it in.

**Comment by szijerveld** [comment]
It should have a picture of the swagger ui like this one.

![swagger_ui_screenshot](https://cloud.githubusercontent.com/assets/6391025/24971097/076699de-1fb7-11e7-8eed-a1ceccefe38f.png)

**Comment by suzannemaquelin** [comment]
Issue was resolved
